### ISSUE TITLE
Telegram API Error: [400] Bad Request: message can't be deleted for everyone

### ISSUE THREAD

**Issue by B1Z0N** [B1Z0N/nevermindybot#1]
After 48 hours the message can't be deleted. Even if you postpone it it is not being deleted from chat.

What to do:

a) Catch and put a message: can't be deleted, pls, remove manually.
b) Edit(is it editable in 48h+?) to something, at least remove buttons so that it's not postponed multiple times.
c) If it's already 47+- hours passed and noone taken any button action, then just resend it at the same interval.

**Comment by B1Z0N** [comment]
Right now [this one](https://github.com/B1Z0N/nevermindybot/commit/3c04e5c3e872a38b596759d3075a7153f7b09a26) fixes it. But it uses generally unhealthy tactic of catching exceptions in control flow. And it worsens a UX a little bit by deleting and resending messages instead of editing them.

So perhaps some more work?

**Comment by B1Z0N** [comment]
And this one [fixes](https://github.com/B1Z0N/nevermindybot/commit/31e55ea3540078bf3dfbe168244ff4a198f0eaeb) it for sure. It adds persistent storage to tie the "resend" job id and the message id to be resent. So now we can cancel the job of reminding us of stalled reminders every 47 hours.

**Comment by bretbas** [comment]
I have the same problem...

**Comment by B1Z0N** [comment]
> I have the same problem...

Any details though? That will help me to help you. I believe that this project uses some logging, so any of that?
